### ISSUE TITLE
GLIBC import error

### ISSUE THREAD

**Issue by David-OConnor** [oberluz/pycoral#7]
Hi! Thank you again for building this! Setup: Ubuntu 20. Python3.11.

Step: `import tflite_runtime.interpreter as tflite`.
Error:
```python
ImportError: /lib/x86_64-linux-gnu/libc.so.6 version `GLIBC_2.34` not found...
```

How would you approach this? Ty!

**Comment by oberluz** [comment]
Hi,

The 3.11 wheels are built using debian bookworm. Look in scripts/build.sh line 47:

`311) echo "debian:bookworm" ;;`

which uses another vuersion of libc as per your error message.
You could try changing that line to ubuntu:20.04 and building it with:

`$ DOCKER_CPUS=k8  scripts/build.sh --python_versions 311`

It may not work because the native python version for ubuntu 20.04 is 3.8
